(display "                   .------.") (newline)
(display ".------.           |A .   |") (newline)
(display "|A_  _ |    .------; / \\  |") (newline)
(display "|( \\/ )|-----. _   |(_,_) |") (newline)
(display "| \\  / | /\\  |( )  |  I  A|") (newline)                            
(display "|  \\/ A|/  \\ |_x_) |------'") (newline)                                     
(display "`-----+'\\  / | Y  A|       ") (newline)                                     
(display "      |  \\/ A|-----'       ") (newline)
(display "      `------'             ") (newline)
(display "♥♦♣♠ Casino Royale ♠♣♦♥") (newline)